workspace 'JuLayout.xcworkspace'

# public specs
# source 'https://github.com/Cocoapods/Specs.git'

platform :ios, '10.0' 
inhibit_all_warnings!
#use_modular_headers!
#use_frameworks!
target 'JuLayoutDemo' do
    pod 'JuLayout', :path => '../'# , :subspecs => ['LayoutSwift']
end



